### ISSUE TITLE
Formatage de la description d'un sondage

### ISSUE THREAD

**Issue by UAPV** [UAPV/RdvZ#1]
From the SourceSup bug tracker (https://sourcesup.cru.fr/tracker/index.php?func=detail&aid=6977&group_id=586&atid=2113) :

Proposée par:
Arnaud Didry (https://sourcesup.cru.fr/users/arnauddidry/)

Les retours à la ligne des descriptions ne sont pas affichés. cette correction pourrait être l'occasion d'intégrer la syntaxe markdown ?

**Comment by romaindeveaud** [comment]
C'est en effet un bug dont la correction sera très prochainement disponible dans les sources.

Merci !
