### ISSUE TITLE
Bloqué après install - répertoire "meeting"

### ISSUE THREAD

**Issue by rjeanson** [UAPV/RdvZ#20]
Bonsoir,

Après installation sans problèmes, je suis bloqué lors de l'authentification (via bdd). Après création d'un user dans la bdd (avec mot de passe codé en sha1), impossible d'accéder à l'application. Firefox m'envoie vers un dossier "meeting" qui n'existe pas.
Pour info, mon dossier /rdvz est à la racine de mon serveur web, qui n'est pas dédié. Pourquoi après m'etre authentifié à la page .../rdvz/web/ le browser me renvoie à l'adresse .../rdvz/web/meeting/ qui n'existe pas ?

Help !!

**Comment by ArnaudD** [comment]
Bonjour,

Ces messages sont dues à une erreur de configuration du mod_rewrite. Plusieurs possibilités :
- fichier .htaccess manquant
- mod_rewrite non activé
- apache refuse les directives du fichiers .htaccess, utilisez `AllowOverride All` dans votre virtual host.

**Comment by rjeanson** [comment]
Ça fonctionne en effet, merci !
Pour info, j'ai du ajouter à mon fichier .htaccess, à la ligne sous "# no, so we redirect to our front web controller" le chemin web vers mon dossier /rdvz/web/, soit pour la ligne entière: "RewriteRule ^(.*)$ /rdvz/web/index.php [QSA,L]"
