### ISSUE TITLE
Hébergement mutualisé OVH

### ISSUE THREAD

**Issue by wr4ch** [UAPV/RdvZ#22]
Bonjour, 

j'aimerais savoir s'il est possible d'installer RdvZ sur des serveurs mutualisés de chez OVH notamment. 

Configuration : 
- Serveur Linux/Apache
- PHP v. 5.3.5

Lorsque je rentre la commande ./INSTALL en ssh voilà ce que j'obtiens : 

./INSTALL: line 1: -=================-: command not found
./INSTALL: line 2: RdvZ: command not found
./INSTALL: line 3: -=================-: command not found
./INSTALL: line 5: Before: command not found
./INSTALL: line 6: especially: command not found
./INSTALL: line 8: When: command not found
./INSTALL: line 9: information: command not found
./INSTALL: line 10: -: command not found
./INSTALL: line 11: syntax error near unexpected token `('
./INSTALL: line 11:` - database user (with privileges !!!)'

Je vous remercie.

**Comment by ArnaudD** [comment]
Bonjour,

Je pense que vous exécutez `./INSTALL.markdown` au lieu de `./install`

Je n'ai pas eu de retours avec OVH, mais en suivant ces instructions cela devrait marcher : http://trac.symfony-project.org/wiki/InstallingSymfonyOnOVH
