### ISSUE TITLE
Problème lors de l'installation.

### ISSUE THREAD

**Issue by shaka-zz** [UAPV/RdvZ#3]
Bonjour, 

merci beaucoup pour le développement. Très beau travail!!!!

J'ai rencontré une erreur lors de l'installation de la nouvelle version de rdvz (2.0.3). Ayant déjà la version 2.0.2 installé, j'ai juste lancé le ./install comme indiqué dans la doc. Cependant, le script d'installation me génère des erreurs sql : 
- SQLSTATE[HY000]: General error: 1005 Can't create table './rdvz/#sql-59d_19a5.frm' (errno: 121). Failing Query: "ALTER TABLE meeting ADD CONSTRAINT meeting_uid_user_id FOREIGN KEY (uid) REFERENCES user(id) ON DELETE CASCADE"
  - SQLSTATE[HY000]: General error: 1005 Can't create table './rdvz/#sql-59d_19a5.frm' (errno: 121). Failing Query: "ALTER TABLE meeting_date ADD CONSTRAINT meeting_date_mid_meeting_id FOREIGN KEY (mid) REFERENCES meeting(id) ON DELETE CASCADE"
  - SQLSTATE[HY000]: General error: 1005 Can't create table './rdvz/#sql-59d_19a5.frm' (errno: 121). Failing Query: "ALTER TABLE meeting_poll ADD CONSTRAINT meeting_poll_date_id_meeting_date_id FOREIGN KEY (date_id) REFERENCES meeting_date(id) ON DELETE CASCADE"
  - SQLSTATE[HY000]: General error: 1005 Can't create table './rdvz/#sql-59d_19a5.frm' (errno: 121). Failing Query: "ALTER TABLE meeting_poll ADD CONSTRAINT meeting_poll_uid_user_id FOREIGN KEY (uid) REFERENCES user(id) ON DELETE CASCADE"
  - SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'is_following' already exists. Failing Query: "CREATE TABLE is_following (id BIGINT AUTO_INCREMENT, mid BIGINT, uid BIGINT, PRIMARY KEY(id)) ENGINE = INNODB"
  - SQLSTATE[HY000]: General error: 1005 Can't create table './rdvz/#sql-59d_19a5.frm' (errno: 121). Failing Query: "ALTER TABLE is_following ADD CONSTRAINT is_following_mid_meeting_id FOREIGN KEY (mid) REFERENCES meeting(id) ON DELETE CASCADE"
  - SQLSTATE[HY000]: General error: 1005 Can't create table './rdvz/#sql-59d_19a5.frm' (errno: 121). Failing Query: "ALTER TABLE is_following ADD CONSTRAINT is_following_uid_user_id FOREIGN KEY (uid) REFERENCES user(id) ON DELETE CASCADE"
  - SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'is_following_mid_idx'. Failing Query: "CREATE INDEX is_following_mid_idx ON is_following (mid)"
  - SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'is_following_uid_idx'. Failing Query: "CREATE INDEX is_following_uid_idx ON is_following (uid)".

Merci de votre aide.

Cordialement.

Shaka

**Comment by romaindeveaud** [comment]
Bonjour,

cette erreur n'est pas très problèmatique : votre SGBD tente de créer une table qui existe déjà (à la demande de l'outil de migration de Symfony) et cette création échoue donc. Normalement ça ne devrait pas arriver mais il y a parfois des problèmes lors des migrations.

Pouvez-vous effectuer la requête SQL suivante sur votre base et donner ici votre résultat?

```
select * from migration_version ;
```

Il se peut également qu'il y ait eu des problèmes avec les fichiers de migration, pouvez-vous lister ces fichiers?

```
$ ls lib/migration/doctrine
```

Normalement ce problème devrait être résolu en effectuant la requête SQL suivante :

```
update migration_version set version = 7 ;
```

Puis en testant :

```
$ php symfony doctrine:migrate
>> doctrine  Already at migration version 7
```

**Comment by shaka-zz** [comment]
1. select \* from migration_version ; donne comme résultat '5'

**Comment by shaka-zz** [comment]
1. ls lib/migration/doctrine donne comme résultat : 

1270822446_addmeeting.php
1270822448_addmeetingpoll.php  
1270822450_addfks.php  
1271865780_version7.php
1270822447_addmeetingdate.php  
1270822449_adduser.php
1271865779_version6.php

**Comment by shaka-zz** [comment]
$ php symfony doctrine:migrate donne comme résultat : 
- SQLSTATE[HY000]: General error: 1005 Can't create table './rdvz/#sql-59d_231c.frm' (errno: 121). Failing Query: "ALTER TABLE is_following ADD CONSTRAINT is_following_mid_meeting_id FOREIGN KEY (mid) REFERENCES meeting(id) ON DELETE CASCADE"
  - SQLSTATE[HY000]: General error: 1005 Can't create table './rdvz/#sql-59d_231c.frm' (errno: 121). Failing Query: "ALTER TABLE is_following ADD CONSTRAINT is_following_uid_user_id FOREIGN KEY (uid) REFERENCES user(id) ON DELETE CASCADE"
  - SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'is_following_mid_idx'. Failing Query: "CREATE INDEX is_following_mid_idx ON is_following (mid)"
  - SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'is_following_uid_idx'. Failing Query: "CREATE INDEX is_following_uid_idx ON is_following (uid)"

**Comment by romaindeveaud** [comment]
Avez-vous executé cette requête?

```
update migration_version set version = 7 ;
```

**Comment by shaka-zz** [comment]
Oui j'ai executé cette requête. Le select \* from version donne comme résultat 7.

**Comment by romaindeveaud** [comment]
Et y a -t-il encore des erreurs SQL lorsque vous effectuez un

```
$ php symfony doctrine:migrate
```

?

**Comment by shaka-zz** [comment]
Oui, la commande '$ php symfony doctrine:migrate' donne comme résultat : 

The following errors occurred:                                                                                                                             
- SQLSTATE[HY000]: General error: 1005 Can't create table './rdvz/#sql-59d_255f.frm' (errno: 121). Failing Query: "ALTER TABLE is_following ADD CONSTRAINT is_following_mid_meeting_id FOREIGN KEY (mid) REFERENCES meeting(id) ON DELETE CASCADE"
- SQLSTATE[HY000]: General error: 1005 Can't create table './rdvz/#sql-59d_255f.frm' (errno: 121). Failing Query: "ALTER TABLE is_following ADD CONSTRAINT is_following_uid_user_id FOREIGN KEY (uid) REFERENCES user(id) ON DELETE CASCADE"
- SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'is_following_mid_idx'. Failing Query: "CREATE INDEX is_following_mid_idx ON is_following (mid)"
- SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'is_following_uid_idx'. Failing Query: "CREATE INDEX is_following_uid_idx ON is_following (uid)"

**Comment by romaindeveaud** [comment]
Juste avant le texte `The following errors occurred:` il doit y avoir un message de Doctrine comme par exemple :

```
>> doctrine  Migrating from version 6 to 7
```

Quel est-il pour vous?

**Comment by shaka-zz** [comment]
Voici : 

doctrine  Migrating from version 7 to 8

**Comment by romaindeveaud** [comment]
Ce n'est pas normal mais ce n'est pas très grave. Vous avez juste à exécuter la requête SQL suivante pour ne plus avoir l'erreur :

```
update migration_version set version = 8 ;
```

**Comment by shaka-zz** [comment]
Nickel!!!!! Le script d'installation se déroule sans encombres.

Merci beaucoup.
